name: Mirror to AWS CodeCommit

on:
  push:
    branches:
      - main  # Adjust the branch as needed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "mirroring"
  mirroring:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ SSH_CLONE_URL }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_username: ${{ secrets.SSH_PUBLIC_KEY_ID }}
